### ISSUE TITLE
i want to download master branch from any repo without switching to desktop, suggest script regard it

### ISSUE THREAD

**Issue by mycal123** [d3ward/scriptz#1]
issue download master branch as zip doesn't appear in phone viewport.

**Comment by d3ward** [comment]
In the latest commit i added the script to download a repository zip of master branch . Checkout  the link to quick install the script - > [repoDownload](https://github.com/d3ward/scriptz/raw/master/src/repoDownload.user.js)

**Comment by mycal123** [comment]
Nice ;working
